eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 5000
spring:
  application:
    name: gateway-service
  sleuth:
    sampler:
      probability:  1.0
  zipkin:
    base-url:  http://192.168.37.128:9411
zuul:
  routes:
    api-a:
      path: /user-api/**
      serviceId: trace-a
