spring:
  application:
    name: trace-b
  sleuth:
    web:
      client:
        enable: true
    sampler:
      probability:  1.0
  zipkin:
    base-url: http://192.168.37.128:9411
server:
  port: 8802
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/